version: "3.8"

services:
  taskforce-db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  taskforce:
    image: taskforce
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      taskforce-db:
        condition: service_healthy

volumes:
  db-data:
