version: "3.8"

services:
  nomic-db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nomic:
    image: nomic
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      nomic-db:
        condition: service_healthy

volumes:
  db-data:
